import type { Metadata } from 'next'
import { Inter, Nunito_Sans } from 'next/font/google'
import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'


const inter = Inter({ subsets: ['latin'] })
const nonitosans = Nunito_Sans({
  weight: "400",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nonitosans.className}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
